import { useState, useEffect } from 'react';
import {
    Modal, View, Text, TextInput, TouchableOpacity,
    StyleSheet, ActivityIndicator, KeyboardAvoidingView, Platform, ScrollView,
} from 'react-native';
import { useTheme } from '../context/ThemeContext';
import { sendEmail, logExecution } from '../app/api';
import { supabase } from '../lib/supabase';

const TEMPLATES = [
    {
        label: 'Meeting Request',
        subject: 'Meeting Request — FlowOptix',
        body: 'Hi,\n\nI would like to schedule a meeting to discuss our upcoming project.\n\nCould you please share your availability?\n\nBest regards',
    },
    {
        label: 'Follow-up',
        subject: 'Following up on our conversation',
        body: 'Hi,\n\nI wanted to follow up on our recent conversation.\n\nPlease let me know if you need any additional information.\n\nBest regards',
    },
    {
        label: 'Status Update',
        subject: 'Project Status Update',
        body: 'Hi,\n\nHere is a quick status update on the project:\n\n• Completed: \n• In Progress: \n• Next Steps: \n\nPlease let me know if you have any questions.\n\nBest regards',
    },
    {
        label: 'Report Sharing',
        subject: 'FlowOptix Productivity Report',
        body: 'Hi,\n\nPlease find attached the latest productivity report generated by FlowOptix.\n\nKey highlights:\n• Productivity Score: \n• Tasks Completed: \n• Top Pattern: \n\nBest regards',
    },
];

interface EmailModalProps {
    visible: boolean;
    onClose: () => void;
    onSuccess: (msg: string) => void;
    onError: (msg: string) => void;
    defaultTo?: string;
    defaultSubject?: string;
    defaultBody?: string;
}

export default function EmailModal({
    visible, onClose, onSuccess, onError,
    defaultTo = '', defaultSubject = '', defaultBody = '',
}: EmailModalProps) {
    const { colors } = useTheme();
    const [to, setTo] = useState(defaultTo);
    const [subject, setSubject] = useState(defaultSubject);
    const [body, setBody] = useState(defaultBody);
    const [sending, setSending] = useState(false);
    const [failed, setFailed] = useState(false);
    const [fromEmail, setFromEmail] = useState('');
    const [showTemplates, setShowTemplates] = useState(false);
    const [toError, setToError] = useState('');

    useEffect(() => {
        if (visible) {
            setTo(defaultTo); setSubject(defaultSubject); setBody(defaultBody);
            setFailed(false); setToError(''); setShowTemplates(false);
            supabase.auth.getUser().then(({ data: { user } }) => {
                if (user?.email) setFromEmail(user.email);
            });
        }
    }, [visible]);

    const validateEmail = (v: string) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v.trim());

    const applyTemplate = (t: typeof TEMPLATES[0]) => {
        setSubject(t.subject);
        setBody(t.body);
        setShowTemplates(false);
    };

    const handleSend = async () => {
        setToError('');
        if (!to.trim()) { setToError('Recipient email is required'); return; }
        if (!validateEmail(to)) { setToError('Enter a valid email address'); return; }
        if (!subject.trim()) { onError('Subject is required'); return; }
        if (!body.trim()) { onError('Message body is required'); return; }

        setSending(true); setFailed(false);
        try {
            await sendEmail(to.trim(), subject.trim(), body.trim());
            await logExecution('send_email', { to: to.trim(), subject: subject.trim() }, 'success', `Sent email to ${to.trim()}`);
            onSuccess('Email sent successfully!');
        } catch (err: any) {
            setFailed(true);
            await logExecution('send_email', { to: to.trim(), subject: subject.trim() }, 'failed', `Failed email to ${to.trim()}`);
            onError(err.message ?? 'Failed to send — check your connection');
        } finally {
            setSending(false);
        }
    };

    const s = makeStyles(colors);

    return (
        <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}>
            <KeyboardAvoidingView
                style={s.overlay}
                behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
            >
                <TouchableOpacity style={{ flex: 1 }} activeOpacity={1} onPress={onClose} />
                <View style={s.sheet}>
                    <View style={s.handle} />

                    <View style={s.header}>
                        <Text style={s.title}>✉  Compose Email</Text>
                        <TouchableOpacity style={s.closeBtn} onPress={onClose} testID="email-modal-close-button" accessibilityLabel="email-modal-close-button">
                            <Text style={s.closeBtnText}>✕</Text>
                        </TouchableOpacity>
                    </View>

                    <ScrollView showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled">
                        <TouchableOpacity style={s.templateToggle} onPress={() => setShowTemplates(v => !v)} testID="email-modal-templates-button" accessibilityLabel="email-modal-templates-button">
                            <Text style={s.templateToggleText}>⚡ Quick Templates</Text>
                            <Text style={[s.templateToggleText, { fontSize: 11 }]}>{showTemplates ? '▲' : '▼'}</Text>
                        </TouchableOpacity>
                        {showTemplates && (
                            <View style={s.templatesRow}>
                                {TEMPLATES.map((t, i) => (
                                    <TouchableOpacity key={i} style={s.templateChip} onPress={() => applyTemplate(t)} testID={`email-modal-template-${i}`} accessibilityLabel={`email-modal-template-${i}`}>
                                        <Text style={s.templateChipText}>{t.label}</Text>
                                    </TouchableOpacity>
                                ))}
                            </View>
                        )}

                        {fromEmail ? (
                            <View style={s.fromRow}>
                                <Text style={s.label}>FROM</Text>
                                <View style={s.fromBadge}>
                                    <Text style={s.fromText}>{fromEmail}</Text>
                                </View>
                            </View>
                        ) : null}

                        <Text style={s.label}>TO</Text>
                        <TextInput
                            style={[s.input, toError ? s.inputError : null]}
                            value={to} onChangeText={v => { setTo(v); setToError(''); }}
                            placeholder="recipient@example.com"
                            placeholderTextColor={colors.muted}
                            keyboardType="email-address" autoCapitalize="none" autoCorrect={false}
                            testID="email-modal-to-input" accessibilityLabel="email-modal-to-input"
                        />
                        {toError ? <Text style={s.errorText} testID="email-modal-to-error" accessibilityLabel="email-modal-to-error">{toError}</Text> : null}

                        <Text style={s.label}>SUBJECT</Text>
                        <TextInput
                            style={s.input} value={subject} onChangeText={setSubject}
                            placeholder="Email subject" placeholderTextColor={colors.muted}
                            testID="email-modal-subject-input" accessibilityLabel="email-modal-subject-input"
                        />

                        <Text style={s.label}>MESSAGE</Text>
                        <TextInput
                            style={[s.input, s.bodyInput]} value={body} onChangeText={setBody}
                            placeholder="Write your message here…"
                            placeholderTextColor={colors.muted}
                            multiline numberOfLines={6} textAlignVertical="top"
                            testID="email-modal-body-input" accessibilityLabel="email-modal-body-input"
                        />

                        <TouchableOpacity
                            style={[s.sendBtn, sending && s.sendBtnLoading]}
                            onPress={handleSend}
                            disabled={sending}
                            testID="email-modal-send-button"
                            accessibilityLabel="email-modal-send-button"
                        >
                            {sending ? (
                                <>
                                    <ActivityIndicator color="#fff" size="small" />
                                    <Text style={s.sendBtnText}>Sending…</Text>
                                </>
                            ) : failed ? (
                                <Text style={s.sendBtnText}>↻  Retry Send</Text>
                            ) : (
                                <Text style={s.sendBtnText}>Send Email  ↑</Text>
                            )}
                        </TouchableOpacity>
                    </ScrollView>
                </View>
            </KeyboardAvoidingView>
        </Modal>
    );
}

const makeStyles = (colors: any) => StyleSheet.create({
    overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.65)', justifyContent: 'flex-end' },
    sheet: {
        backgroundColor: colors.card,
        borderTopLeftRadius: 28, borderTopRightRadius: 28,
        padding: 24, paddingTop: 14, maxHeight: '90%',
        borderWidth: 1, borderColor: colors.border,
    },
    handle: {
        width: 44, height: 5, backgroundColor: colors.border,
        borderRadius: 3, alignSelf: 'center', marginBottom: 20,
    },
    header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
    title: { color: colors.text, fontSize: 19, fontWeight: '700' },
    closeBtn: {
        width: 34, height: 34, borderRadius: 17,
        backgroundColor: colors.border, justifyContent: 'center', alignItems: 'center',
    },
    closeBtnText: { color: colors.subtext, fontSize: 13, fontWeight: '700' },

    templateToggle: {
        flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
        backgroundColor: 'rgba(124,92,255,0.1)', borderRadius: 10,
        paddingHorizontal: 14, paddingVertical: 10, marginBottom: 10,
        borderWidth: 1, borderColor: 'rgba(124,92,255,0.25)',
    },
    templateToggleText: { color: colors.accent, fontSize: 13, fontWeight: '600' },
    templatesRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 14 },
    templateChip: {
        backgroundColor: colors.bg, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 7,
        borderWidth: 1, borderColor: colors.border,
    },
    templateChipText: { color: colors.text, fontSize: 12 },

    fromRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 14 },
    fromBadge: {
        backgroundColor: colors.bg, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8,
        borderWidth: 1, borderColor: colors.border, flex: 1,
    },
    fromText: { color: colors.muted, fontSize: 13 },

    label: { color: colors.muted, fontSize: 10, fontWeight: '700', letterSpacing: 1.5, marginBottom: 7 },
    input: {
        backgroundColor: colors.bg, color: colors.text,
        borderRadius: 12, padding: 14, marginBottom: 14,
        fontSize: 14, borderWidth: 1, borderColor: colors.border,
    },
    inputError: { borderColor: colors.danger },
    errorText: { color: colors.danger, fontSize: 12, marginTop: -10, marginBottom: 10 },
    bodyInput: { height: 130, paddingTop: 12 },

    sendBtn: {
        backgroundColor: colors.accent, borderRadius: 14, padding: 17,
        alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 10,
        marginTop: 4, marginBottom: 8,
    },
    sendBtnLoading: { opacity: 0.75 },
    sendBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },
});
